.PHONY: test server cache-clear install help

.DEFAULT_GOAL= help

PORT?=8000
HOST?=127.0.0.1

#PHP=php
#CURRENT_DIR=$(shell pwd)
#ifdef VERSION
#    PHP=docker run -it --rm --name phpcli -v $(CURRENT_DIR):/usr/src/myapp -w /usr/src/myapp php:$(VERSION)-cli php
#endif


composer.lock: composer.json
	composer update

vendor: composer.lock
    composer install

install: vendor

help: 
	@grep -E '(^[a-zA-Z_-]+:.*?##.*$$)|(^##)' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[32m%-10s\033[0m %s\n", $$1, $$2}' | sed -e 's/\[32m##/[33m/'

#test: install ## Lance les tests unitaire
#	php ./vendor/bin/phpunit --stop-on-failure

cache-clear: ## Nettoie le cache
	rm -rf ./tmp

server: install ## Lance le serveur interne de PHP
    echo -e "Lancement du serveur sur $(OK_COLOR)http://$(HOST):$(PORT)$(NO_COLOR)"
    ENV=dev $(PHP) -S $(HOST):$(PORT) -t public/ -d display_errors=1